apiVersion: ENC[AES256_GCM,data:RuA=,iv:l4iXZcGm+yfzrshu28Dzw6C6FmXl+hxn37pNpP8e8mg=,tag:VAr4GgWoUozF0FVBUb6S+A==,type:str]
kind: ENC[AES256_GCM,data:U2XVc/HY,iv:YmsKGOddCJV674vqr/KxQc3v/Hd5QXcJaOxABSUIuk0=,tag:AB2R96fDiDB351re7e5Zmg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mimYxy6A5FXnoIYF2A==,iv:9izRIlZIVcESjGxJqyuKavc2NEF8xdM/1vUdgOhDfOQ=,tag:o0YPahDFQUPnXCVns5sqZg==,type:str]
    namespace: ENC[AES256_GCM,data:cUxUcLxk5CC9PVeOQFxjHOyIpJpvu8i0NCofINUgO/g=,iv:5FYPWOPLy1V2amlUTjXLX4V7lUyW2MN6fSXTNEHHGNM=,tag:nNy2TIyx6ni+l/WjuOwKqg==,type:str]
type: ENC[AES256_GCM,data:xDqsgKYr,iv:EyFMfZtdTCU2VPmyqNf23Zh4S9oS1gROiPEna0x1JLA=,tag:zp4VeJnEpnMTKQfET9N1pw==,type:str]
stringData:
    AMD_LLM_KEY: ENC[AES256_GCM,data:Sb6CIx5LRl+nM2o7LTOly+OtkOAx064nTTp9hthhFPA=,iv:uKtLqTG9MRbZ9wG2aWFGuIujF0PbHEeLF7e/4BoeFQo=,tag:MHu+jNQLxdZTc72jazoM5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tj59vuw9yh8lle0ty43ep2092n0n05mj96jzkfcle5d0u7fuu3qqxj6v5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU2RTcGtUR2xUR0U5Tndp
            b3kwY2JLanZjNmZGS0liT01HT1NCa0xpZlF3CmkxZTU4UlhxT1o4a1Vhd1BVK05P
            bVlaekN6K0RHYk9FcHNGdzl4K2RTZGcKLS0tIGZvaVRjMU5vaEJuME9QYVhwZXNU
            MVBXanlSc3BzZWxLU1NScWtvTGUzdzgK3AEY56oxFkv8mVjb+pfXpuWwDy+i6ARe
            /QtRfZbf5vGg7JEmpq2OUftivF3PrYaf4cs10Gf4JLWmFlIcm0hvGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:59:25Z"
    mac: ENC[AES256_GCM,data:TC/LaQUZOK9jM3As4wVlvm3AY74FuOV2wBpUe75Lm2Zf6rSKV05kdflq6/4lkge9ej0vBNJQ/m/o5MKq1jnXyEPD4fHdLj0ZI8HraFur0crwFkdCJRf2HNL6ocQjH3hW1QDN7h2ZiHi/J1TShe0ONjDocNT0/bAS1abvUGo3UUY=,iv:0f3Y8xDEZ9MH2MI4cYOzfz4GyJJY/ypvZ3MAh4itjFE=,tag:to2o7Z9QzgufE+Amts/MQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
