apiVersion: ENC[AES256_GCM,data:Wag=,iv:t1BIAB0Vt5SLSZXufJrHAqltMKsTcBzXlz03pGjdaEw=,tag:j8k+d5d6arzuJiwnYM2GpA==,type:str]
kind: ENC[AES256_GCM,data:QgdlF4HL,iv:VHUoM+PmTIkof3ErDbJHB7CwSjXkkpyPYqcwt4vWFQA=,tag:tMsfjWD/FFGwSb4DYyxOHw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KYP5+bH+sVgbgNGz7w==,iv:qFeKZ1aJV2hKpYWXGtAPnJLzLy7LKrV3aXIzxlVqGBc=,tag:cgn7HpyWfh0eM7dy8GTzsQ==,type:str]
    namespace: ENC[AES256_GCM,data:McWHDSKHoQ3nJEZrzA==,iv:MiRgnr/faSWSwb7s3qp0aTCPm/3I7pWBJzmlQbaQ+FU=,tag:yx8WH35DJ/jiVFWbvZ62kw==,type:str]
type: ENC[AES256_GCM,data:E9GYzZlL,iv:MWvQJfqgmkexcSkYCapVI/y34ZqaWRwZdgugssHDxuA=,tag:gVok4xi+VyGeTDLuLwSGHw==,type:str]
stringData:
    AMD_LLM_KEY: ENC[AES256_GCM,data:B2ZXjvaIZYCiy+8AxjEyMjxmVGTGW5cleBs98mcq/0o=,iv:PhJ7nI+UBSyFrTo8qFq0eU35Iv4iBFbOp5bPsq+L9W8=,tag:jt6EUZf8ngTyFPwrBOdwxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r5cjptkyd4wn82y5flfte4lm7y67nk2wxqhm7ncg5v23ea6seq9sfyjl0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcTJDbkk3MkQwYlRwMEJq
            dkZFMkNhcy94bUs2RmZwdDJDaW13cnRVd2xVCkZzTTc2QitPdFZzRUpxSWJuYjgy
            NkhHdFFQeDVyVWc1MjlOUm9tN2FkemsKLS0tIHhhRXoyTUUwLzExVHRvUEVYdm40
            RzhQNmxJZis4bEZoaEx3bmR2aGl2RDgK7bd4C95LfhNLOEutLkHfOz0MwUTl4Yk8
            p/jgDaNDjdAeQHbOFT6+VlA3Y1uvr2ugnV2KTgae8Z/EdA5gdCREyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T19:53:39Z"
    mac: ENC[AES256_GCM,data:CaxyENCCrBwA8cMGxEozygEk6bEMyUTHlxU/yX6jWMHvNy4oyen3WF8NTduaSM68a2BE91NJ/6oI0/lLk6y0JWBZhkasHhg5Cz76mH09Zh0j+NS1Xowxw2LqcCVAJp6bSA5i68ya0D9Ab7/Vbpyghli5GYjoVKyHxcM+eaJMkEA=,iv:I3NYdf8C/ExDBOSBgNA/n/YuRlfbVrXgoBzV2Gs367g=,tag:4+OX499YOLPiNSbOrmXkrg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
